# Generated by Django 4.1.7 on 2023-03-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_waste_cat_alter_waste_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
